### ISSUE TITLE
What if over 100 jobs are executed in a GitHub workflow...

### ISSUE THREAD

**Issue by hwhsu1231** [Tiryoh/gha-jobid-action#43]
### Problem Description

Hello, gha-jobid-action maintenance team.

From the discussion results of this [issue](https://github.com/Tiryoh/gha-jobid-action/issues/35#issuecomment-1982950268), it seems that the current capability of gha-jobid-action (`v1.2.0`) to handle the maximum number of jobs in a GitHub workflow is **100** (with `per_page: 100`).

Of course in practical applications, it is almost unlikely to encounter a case where more than 100 jobs are executed in a single workflow.

However, I would like to confirm, assuming such an extreme case does happen one day, looking at the interface provided by the GitHub API as it stands, is there a way to cope?

**Comment by Tiryoh** [comment]
Hi @hwhsu1231 

The value specified in this `per_page` parameter is passed directly to the REST API query.
Since the REST API limit is 100, this action has the same limit.

![image](https://github.com/Tiryoh/gha-jobid-action/assets/3256629/a6cb12b2-55e7-4966-a24d-731c5ef5de59)
https://docs.github.com/en/rest/actions/workflow-jobs?apiVersion=2022-11-28

If someone has a request to use this tool with more workflows than 100, I would be happy to work with to find a way to implement it. :smiley:

**Comment by abower-digimarc** [comment]
I use this, and my actions kick off up to 164 jobs in one run. So, I either have to write my own version, OR, I'd suggest you implement pagination.

Essentially, 'if no job id found, rerun with &page=2', iterating up

**Comment by hwhsu1231** [comment]
Hello, @Tiryoh 

> If someone has a request to use this tool with more workflows than 100, I would be happy to work with to find a way to implement it. 😃

I think I've finally reached the point where I have to consider the situation of having more than 100 jobs.

Consider that I have to build CMake Documentation from `v3.0` to `v3.29`, including `latest` and `master`. Let's say there are **32** versions in total (which will increase as time goes on). And suppose that I want to build **3** languages, e.g. `ja`, `zh_CN`, and `zh_TW`. Just the scenario mentioned above, the `strategy.matrix` already has **32x3=96** combinations.

If a new language (`ru`) is added, then the `strategy.matrix` will reach **32x4=128** combinations, which cannot be handled by [gha-jobid-action@v1.2.0](https://github.com/Tiryoh/gha-jobid-action/tree/v1.2.0).

Therefore, I want to ask how confident you are in improving this GitHub Action to handle more than 100 jobs?

**Comment by qoomon** [comment]
You could use `qoomon/actions--context@v4` action to add additional environment variables.It will work also with matrix jobs and within reusable workflows. And it works with any amount of job within a workflow run

```yaml
jobs:
  example:
    runs-on: ubuntu-latest
    environment: playground
    steps:
      - uses: qoomon/actions--context@v4
      - run: |
          echo "Job Id:         ${GITHUB_JOB_ID}"
          echo "Job Name:       ${GITHUB_JOB_NAME}"
          echo "Job Log URL:    ${GITHUB_JOB_URL}"
          echo "Environment:    ${GITHUB_ENVIRONMENT}"
          echo "Deployment URL: ${GITHUB_DEPLOYMENT_URL}"
```

This action determines the current job by listing all job of current workflow with current run id and then finds current job by matching the runner name or id.

Source: https://github.com/qoomon/actions--context
